backend:
  name: git-gateway
  branch: main   # или ваша ветка

media_folder: "images"        # куда грузить файлы в репо
public_folder: "/images"      # как на них ссылаться в сайте

locale: "ru"
publish_mode: editorial_workflow  # черновик → публикация (можно убрать)

collections:
  - name: "projects"
    label: "Проекты"
    label_singular: "Проект"
    folder: "data/projects"
    create: true
    format: "json"           # файлы карточек будут JSON
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Заголовок", widget: "string" }
      - { name: "date", label: "Дата", widget: "datetime", format: "YYYY-MM-DD" }
      - { name: "cover", label: "Обложка", widget: "image" }
      - { name: "gallery", label: "Галерея", widget: "list", field: { name: "image", label: "Изображение", widget: "image" } }
      - { name: "scale", label: "Масштаб (например 1/10)", widget: "string", required: false }
      - { name: "paints", label: "Краски/материалы", widget: "list", required: false, field: { name: "item", label: "Пункт", widget: "string" } }
      - { name: "steps", label: "Шаги/описание", widget: "list", required: false, field: { name: "text", label: "Шаг", widget: "text" } }
      - { name: "tags", label: "Теги", widget: "list", required: false }
      - { name: "published", label: "Публиковать", widget: "boolean", default: true }
      - { name: "order", label: "Порядок (сортировка)", widget: "number", required: false }
